name: Spring Boot Tests and Vulnerability Scans
run-name: Spring Boot Tests and Vulnerability Scans

permissions:
  security-events: write
  actions: read
  contents: read

on:
#  pull_request:
#    types:
#      - opened
#      - reopened
#    branches:
#      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn test

  dependencyCheck:
    needs: test
    name: Dependency Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'spring-boot-backend'
          path: '.'
          format: 'ALL'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Dependency Check results
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports

  fsScan:
    needs: dependencyCheck
    name: File System Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-fs-scan-results.sarif"
          severity: "CRITICAL"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-fs-scan-results.sarif"

  containerScan:
    needs: test
    name: Container Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t spring-boot-backend-image .
      - name: Run Trivy container vulnerability scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "spring-boot-backend-image"
          scan-type: "image"
          format: "sarif"
          output: "trivy-image-scan-results.sarif"
          severity: "CRITICAL"
      - name: Upload Trivy container scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-image-scan-results.sarif"